# Site settings
title: marcus and pecan, a history
email: hello@victoriasun.io
description: > # this means to ignore newlines until "baseurl:"
  happy valetine's day, alicia
baseurl: "/marcan" # the subpath of your site, e.g. /blog/
url: "http://victoriasun.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
